### ISSUE TITLE
Python basics checklist

### ISSUE THREAD

**Issue by lucydot** [NU-CEM/CompPhys#20]
### Running Python | [Tutorial](https://nu-cem.github.io/CompPhys/2021/08/02/01-Running_Python) | [Quick test questions](https://nu-cem.github.io/CompPhys/2021/08/02/01-Running_python-Qs.html)

- [x] Open and save a Jupyter Notebook
- [x] Use basic Markdown in a notebook
- [x] Run Python cells in a notebook

### Variables and assignment | [Tutorial](https://nu-cem.github.io/CompPhys/2021/08/02/02-Variables-Assignment) | [Quick test questions](https://nu-cem.github.io/CompPhys/2021/08/02/02-Variables-Assignment-Qs.html)

- [ ] Write a program that assigns scalar values to variables
- [x] Use valid and meaningful variable names
- [ ] Perform calculations with the values
- [x] Correctly trace value changes in programs that use scalar assignment
- [ ] Use the `print` function to print out values

### Data types and type conversion | [Tutorial](https://nu-cem.github.io/CompPhys/2021/08/02/Data-Types) | [Quick test questions](https://nu-cem.github.io/CompPhys/2021/08/02/Data-Types-Qs.html)

- [x] Explain the difference between integer numbers and floating point numbers
- [x] Explain the difference between numbers and character strings
- [x] Find the type of a value using the `type` function
- [ ] Manipulate strings using `*` and `+` operators
- [ ] Select a single character from a string using indexing
- [ ] Select a substring using slicing
- [ ] Find the length of a string using the `len` function
- [ ] Use built-in functions to convert between integer numbers, floating point numbers and strings

### Built-in functions, help and errors | [Tutorial](https://nu-cem.github.io/CompPhys/2021/08/02/Functions) | [Quick test questions](https://nu-cem.github.io/CompPhys/2021/08/02/Functions-Qs.html)

- [ ] Expain the difference between built-in functions, library functions and custom-made functions
- [ ] Explain the purpose of functions
- [ ] Correctly nest calls to built-in functions
- [ ] Use the `round` function to round a float to a given number of significant figures
- [x] Use help to display documentation for built-in functions
- [x] Describe situations in which SyntaxError and NameError occur

### Lists | [Tutorial](https://nu-cem.github.io/CompPhys/2021/08/02/Lists) | [Quick test questions](https://nu-cem.github.io/CompPhys/2021/08/02/Lists-Qs.html)

- [x] Give examples where programs need collections of values 
- [x] Create a Python list
- [x] Explain the difference between 'indexing from one' and 'indexing from zero'
- [ ] Select an item from a list using indexing
- [ ] Assign new values to items in a list
- [ ] Explain the difference between mutable and immutable types
- [ ] Use the `append` method to add items to a list
- [ ] Explain the difference between a method and a function
- [ ] Use `del` to remove an item from a list

### Programming good practice 

- [x] Use `#` to add in-line documentation to programs
- [x] Use docstrings to provide help documentation for custom functions
- [ ] Use markdown to describe program behaviour and design decisions
- [ ] Use assert statements for testing
- [ ] Use `.__version__` to print library version numbers
- [ ] Use consistent and appropriate whitespace
